### ISSUE TITLE
Default provider enhancement

### ISSUE THREAD

**Issue by zekth** [SerayaEryn/fastify-session#100]
Default provider is nice but as said in documentation:
```
Defaults to a simple in memory store.
Note: The default store should not be used in a production environment because it will leak memory.
```

We can fix this issue in a non intrusive way by passing the `Map` of the store we want to use. Currentyl it uses an `Object` (ref: https://github.com/SerayaEryn/fastify-session/blob/master/lib/store.js#L7 ) but implementing a `Map` would give use the possibility to use this kind of library: https://github.com/rsms/js-lru

By this way we will not have any memleak. The Store object just needs to implement the [Map API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)

Also having the store reference accessible outside the middleware would make possible to access the number of current sessions in the store.

What's your thoughts @SerayaEryn ? I can work on this.

**Comment by SerayaEryn** [comment]
If this can be done without changing the API of the Store(s), please feel free to open a PR.
