### ISSUE TITLE
How to implement "remember me"?

### ISSUE THREAD

**Issue by mfpopa** [SerayaEryn/fastify-session#106]
My plugin configuration is:

```typescript
fastify.register(fastifySession, {
  secret: process.env.SESSION_SECRET,
  cookieName: 'auth',
  cookie: {
    httpOnly: true,
    sameSite: true,
    secure: process.env.NODE_ENV === 'production',
  },
  saveUninitialized: false,
  store: new SessionStore(),
});
```
This works well. It creates a session that is expires when the browser is closed. All good so far.

What I want to do next is to enable people who log in using the `remember me` checkbox to stay logged in even after they close the web browser, but come back within 14 days.

Here is what I tried:

```typescript
if (remember) {
  request.session.cookie.maxAge = COOKIE_AGE;
  request.session.cookie.expires = new Date(Date.now() + COOKIE_AGE);
  request.session.touch();
}
```

From inspecting the source code it seems to me that the [Session constructor](https://github.com/SerayaEryn/fastify-session/blob/cd1c40f3db948a418f17568530e0dd34f354c45a/lib/session.js#L13) is the problem because it resets the cookie and `maxAge` to the defaults instead of using the properties of the `prevSession`.

A possible fix I think could be changing the following in the Session constructor:

```typescript
this.cookie = new Cookie(prevSession.cookie || cookieOpts)
this[maxAge] = prevSession.expires ? new Date(prevSession.expires).getTime() : cookieOpts.maxAge
```

Am I doing this wrong or this not a scenario that has been considered?

I am happy to submit a PR. I am aware that this may be a breaking change.

It is quite important for me because I am finalising a large project using Fastify. If it does not get resolved by June, then I will fork this so no big deal, but it would be nice to not have to fork it.

**Comment by bardak-dev** [comment]
@mfpopa You could try set options.cookie.maxAge= 10 * 365 * 24 * 60 * 60 * 1000 (example for ten year, feel free to increase the value). Works fine for me.

**Comment by mfpopa** [comment]
I have come up with a solution that does not require a change to the plugin.

Since I am implementing my own session store using Mongo, in the `set(id, session, callback)` method I can control the expiration date of the cookie given that I am saving the `remember me` option on the session.

```typescript
// in login route
...
if (rememberMe) {
  request.session.user.remember = true;
}
...
```
```typescript
// in session store
set(sessionId: string, session: Session, callback: (err?: Error) => void) {
  if (session.user && session.user.remember) {
    session.cookie.expires = new Date(Date.now() + COOKIE_AGE);
    session.expires = session.cookie.expires;
  }
  ...
}
```

I am closing this just because I have my solution, even though I would still like to know if there is a better way to do this.
