### ISSUE TITLE
connect-mongo store throwing error

### ISSUE THREAD

**Issue by Dannybrown2710** [SerayaEryn/fastify-session#107]
const MongoStore = require('connect-mongo')(fastifySession);

I have used connect-mongo and got an error
Users/xyz/Documents/app/node_modules/connect-mongo/src/index.js:59
  const MemoryStore = connect.MemoryStore || connect.session.MemoryStore

TypeError: Cannot read property 'MemoryStore' of undefined

**Comment by mfpopa** [comment]
`connect-mongo` [expects](https://github.com/jdesboeufs/connect-mongo/blob/d33bbb38a4acbddc0e53b3a074780d620ba76bf9/src/index.js#L58) the parameter you pass in `require('connect-mongo')(____here____)` to have a `MemoryStore` property which the fastify-plugin does not provide. So based on this it's clear to me that `fastify-session` cannot be used with `connect-mongo`.

For my application, I ended up creating my own session store copying what connect-mongo is doing.

**Comment by Dannybrown2710** [comment]
Yes, I tried using the default session store provided by mongojs

**Comment by SerayaEryn** [comment]
This problem should be fixed in v4.0.1
