### ISSUE TITLE
Cookie not saved in browser

### ISSUE THREAD

**Issue by ghost** [SerayaEryn/fastify-session#11]
Hi, below is 2 section of code, the referURL  is null due to Cookie not saved in browser
please take a look, thanks

	if(request.session.user === undefined){
		request.session.referURL =  '/displayUpload';
		reply.redirect('/login.html');
		return;
	}

...

if(loggedin){
			request.session.user = username;
			var url = request.session.referURL
			if(!(url === undefined)){
				reply.redirect(url);
				return;
			}else{
				reply.redirect('/home');
				return;
			}
			
		}

**Comment by SerayaEryn** [comment]
@dsun9 I guess you have a insecure request but the `secure` cookie option isn't set to false (it defaults to `true`).

If my guess is right please try to pass secure=false with the options like this:

```js
const options = {
  secret: 'a secret'
  cookie: {
    secure: false
  }
}
app.register(fastifySession, options);
```

**Comment by ghost** [comment]
Thanks. I wish I got your reply sooner, but no complaining. it seems to work, but I need to revert back all my code to test as I had switched to another approach. will test and close shortly

**Comment by ghost** [comment]
it works, thanks.
