### ISSUE TITLE
fastify v3 d.ts support

### ISSUE THREAD

**Issue by CreeJee** [SerayaEryn/fastify-session#115]
fastify: ^3.0.2
fastify-session: ^4.0.1

please...

**Comment by zekth** [comment]
Working on the port right now.

**Comment by mfpopa** [comment]
Can we get the linked pull request reviewed and accepted. I am just upgrading from fastify v2 to v3 and this plugin fails type checking.

**Comment by zekth** [comment]
You can declare the plugin `as any` or add a `//@ts-ignore` before the typings get merged.
