### ISSUE TITLE
sqlite3 session stores .

### ISSUE THREAD

**Issue by ghost** [SerayaEryn/fastify-session#13]
Hi,
can this be used with sqlite3 ? could you kindly provide a example? Thanks

**Comment by zenflow** [comment]
@dsun9 The readme says ["Compatible to stores from express-session."](https://github.com/SerayaEryn/fastify-session#store) so here is [a list of compatible session stores](https://github.com/expressjs/session#compatible-session-stores)

I think you will want to use https://github.com/rawberg/connect-sqlite3

**Comment by ghost** [comment]
I tried
const session = require('fastify-session')
var  SQLiteStore = require('connect-sqlite3')(session);
and
var  SQLiteStore = require('connect-sqlite3')(fastify);

got error

\node_modules\connect-sqlite3\lib\connect-sqlite3.js:80
    SQLiteStore.prototype = Object.create(Store.prototype);
                                                ^

TypeError: Cannot read property 'prototype' of undefined
    at module.exports (node_modules\connect-sqlite3\lib\connect-sqlite3.js:80:49)
    at Object.<anonymous> (app.js:8:46)

**Comment by SerayaEryn** [comment]
@dsun9 I looked into this. express-session exports the `Store` property to allow stores to inherent from it.
I published a update to fix this problem. `fastify-session` now also exports a `Store` property. Please update to v0.2.2.

This works now:
```js
const session = require('fastify-session')
const SQLiteStore = require('connect-sqlite3')(session);
```

**Comment by ghost** [comment]
Thanks. the compile error is gone. However, I saw 2 different errors when I tried 2 pages.

1. This page isn’t working localhost is currently unable to handle this request. HTTP ERROR 500
2. {"error":"Internal Server Error","message":"Cannot read property 'maxAge' of undefined","statusCode":500}

**Comment by SerayaEryn** [comment]
I've installed sqlite3 to reproduce the error. I found the problem, fixed it and published an update.  
In my test app with `connect-sqlite3` is working now.

**Comment by ghost** [comment]
cool, it works, thanks
