### ISSUE TITLE
[Question] Cookies options not clear to me

### ISSUE THREAD

**Issue by thegoldgoat** [SerayaEryn/fastify-session#136]
I don't understand how to handle cookies' properties (sameSite & secure) during development vs production

In production the fastify server is behind an nginx reverse proxy connected via HTTP, so I set secure true and SameSite None

But during development I don't use any proxy and connect directly with HTTP

**Comment by gmencz** [comment]
You can set the cookie options based on the environment:
```js
const cookieOptions = {
    secure: process.env.NODE_ENV === 'production',
    ...
}
```

**Comment by thegoldgoat** [comment]
Thanks for the response, that's a nice solution actually!

However, the real problem for me was http localhost development, which I guess can only be done in Firefox as of now (I mean, cross-site cookies, the rest works)

It looks to me that it is just a browser rule, so we just have to deal with it. Closing the issue now
