### ISSUE TITLE
save session to cookie (signed/encrypted)

### ISSUE THREAD

**Issue by ghost** [SerayaEryn/fastify-session#14]
Hi, I tried the store option with sqlite, it is a little slow. I'm wondering if there could be an option to save session to cookie (signed/encrypted) as many cases only have small data.

Thanks.

**Comment by SerayaEryn** [comment]
I think with a little adaption it should be possible to write a store that saves the data in a cookie. 

I'll take a closer look tomorrow.

**Comment by SerayaEryn** [comment]
My idea to create a store that the data in a cookie didn't work.

You could use [fastify-secure-session](https://www.npmjs.com/package/fastify-secure-session) if you want to save the session in a cookie.
Or you could use something like redis to save the session.

**Comment by ghost** [comment]
Thanks for your suggestions
