### ISSUE TITLE
Having problems with the session store

### ISSUE THREAD

**Issue by robinrossow** [SerayaEryn/fastify-session#162]
Hey,

I'm trying to use a session store and I'm currently using this code:

```
const fastifySession = require('fastify-session')
const fastifyCookie = require('fastify-cookie')

const redis = require('redis')
const redisClient = redis.createClient()
const RedisStore = require('connect-redis')(fastifySession)

app.register(fastifySession, {
  secret: 'some secret',
  cookieName: 'some name',
  cookie: {
    secure: true,
    httpOnly: true
  },
  saveUninitialized: false,
  store: new RedisStore({
    host: 'localhost',
    port: 6379,
    client: redisClient,
    ttl: 600
  })
})
```

And I'm noticing two problem:

1.  The store doesn't seem to be used at all. 
2. I get this error when starting fastify: 
`FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead. Property: sessionStore
`

Did I do anything wrong? It would help immensely to have a session store example in the docs.

I'm using the following versions:
```
 "fastify": "3.15.1"
 "fastify-cookie": "5.3.1"
 "fastify-session": "5.2.1"
```

**Comment by whoisjuan** [comment]
@robinrossow How did you fix this? I saw you closed it and I'm having the same problem. Any help would be tremendously appreciated.
