### ISSUE TITLE
Redis session store

### ISSUE THREAD

**Issue by selesh3** [SerayaEryn/fastify-session#26]
I tried to use connect-redis

`const fastify = require('fastify')()
const fastifySession = require('fastify-session')
const fastifyCookie = require('fastify-cookie')
const RedisStore = require('connect-redis')(fastifySession)
const redis = require('redis')

const redisClient = redis.createClient()

const sessionOptions = {
	secret: 'key',
	store: new RedisStore({
		host: 'localhost',
		port: 6379,
		client: redisClient,
		ttl: 600
	}),
	cookieName: 'sesId',
	cookie: {
		secure: false,
		httpOnly: false,
		domain: 'localhost',
		path: '/'
	}
}

fastify.register(fastifyCookie)
fastify.register(fastifySession, sessionOptions)`

But I got a error

/node_modules/connect-redis/lib/connect-redis.js:129
      self.emit('connect');
           ^

TypeError: self.emit is not a function

I will appreciate if you can help with it

**Comment by SerayaEryn** [comment]
I'll take a look at this problem.

**Comment by SerayaEryn** [comment]
I published a fix for this problem.

**Comment by selesh3** [comment]
Works great. Thanks!
