### ISSUE TITLE
Feature request: Don't start session if not initialised option

### ISSUE THREAD

**Issue by Green-Cat** [SerayaEryn/fastify-session#36]
It would be useful to add an option not to start a session (and set a cookie) if nothing is written into the session during the handling of the request.

This option would avoid wasting storage space in the store with empty sessions for non-signed in users and help comply with the EU cookie law. express-session, which this module seems to draw a lot from, has this in the "saveUninitialized: false" option.

**Comment by SerayaEryn** [comment]
I agree. This would be a good thing to have as an option.

Do you wish to open a PR? If not I'll take a look at it.

**Comment by Green-Cat** [comment]
Sorry for the late reply, got busy with work.
I've submitted a PR to add this functionality:  #37
