### ISSUE TITLE
fastify-session will throw error if post a request without param

### ISSUE THREAD

**Issue by woxixiulayin** [SerayaEryn/fastify-session#4]
hi there,
    in my project, it will throw an error if  fire a post request without param, it will throw error like this:
```
        const session = request.session;
                                ^
TypeError: Cannot read property 'session' of undefined
```
    can you fix it? thank you.

**Comment by SerayaEryn** [comment]
I'll take a look at it.

**Comment by SerayaEryn** [comment]
This seems to be a problem in fastify itself. I opened an issue in the fastify repository.

For the meantime I wrote a workaround to avoid this error happening and published it. Please be aware that I can not write the session cookie in this case if the request is `undefined`.

**Comment by SerayaEryn** [comment]
Fixed in v.0.1.1
