### ISSUE TITLE
Session touched on every request

### ISSUE THREAD

**Issue by shaungrady** [SerayaEryn/fastify-session#42]
I noticed in `1.2.0` a new `touch` Session instance method was added. However, I noticed that, on every request, the `expires` property gets touched anyway.

Is this by design? Or should the session expiry remain unchanged until `session.touch()` or `sessionStore.set()` is called?

**Comment by SerayaEryn** [comment]
Actually there is no particular reason.
If needed the `expires` property may remain unchanged until `sessionStore.set()` is called.

Please feel free to open a PR.

**Comment by SerayaEryn** [comment]
I am closing this issue.

If needed please reopen it or open a new one.
