### ISSUE TITLE
Can't store data in session

### ISSUE THREAD

**Issue by Banonevar** [SerayaEryn/fastify-session#50]
Hi!
I can't save my data to session. Here is my code
```javascript
const fastify = require('fastify')()
const fastifySession = require('fastify-session')
const fastifyCookie = require('fastify-cookie')
fastify.register(fastifyCookie)
fastify.register(fastifySession, { secret: 'my long 32 digit secret' })

fastify.addHook('preHandler', (request, reply, next) => {
  if (request.session.views) {
    request.session.views++;
  } else {
    request.session.views = 1;
  }

  next();
});

fastify.get('/', function (request, reply) {
  console.log(request.session.views)
  reply.send(request.session.views)
})

fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})
```

And my request.session.views always 1
![img](https://i.imgur.com/BFP6C4M.png)

### My Environment 
Node.js - v11.11.0
"fastify": "^2.1.0",
"fastify-cookie": "^3.0.2",
"fastify-session": "^2.0.0"

**Comment by pndewit** [comment]
Could you try to set the `secure` option to false (it is on by default). I expect you are on an insecure connection (localhost?). You can disable it like this:

```
app.register(fastifySession, {
  secret: 'my long 32 digit secret',
  cookie: {
    secure: false,
  },
});
```

**Comment by Banonevar** [comment]
Yea, im testing it on localhost, will set secure to false.
Guess devs need specify this information in docs for noobs like me xD

**Comment by Banonevar** [comment]
Yea it helped, thx!

**Comment by pndewit** [comment]
True, you're not the first one to ask.
https://github.com/SerayaEryn/fastify-session/pull/51
