### ISSUE TITLE
How to access to `req.session` outside Routes

### ISSUE THREAD

**Issue by dalisoft** [SerayaEryn/fastify-session#52]
Hello and thanks for nice library.
I am looking for getting the session store to accessing within websocket, but seems it's impossible.

There has solution?

My code snippet:

```js
const {corsWhitelist} = require('../config');
const wsWrap = require('../helpers/ws');
const {cookie} = require('../helpers');
const Server = require('ws/lib/websocket-server');

module.exports = (fastify) => {
  const onlineClientsMap = {};

  fastify.ws = (path, fn) => {
    const reqCache = {};
    const wss = new Server({
      verifyClient: (info, done) => {
        if (!info.req.cookies) {
          info.req.cookies = cookie.getCookieFromHeaders(info.req);
        }
        const {sessionId} = info.req.cookies;

        const intervalId = setInterval(() => {
          const session = reqCache[sessionId];
          if (session) {
            info.req.session = session;
            clearInterval(intervalId);
            done(true);
          }
        }, 1000);
      },
      server: fastify.server,
      path,
    });

    // i think this is solution, but it isn't, because WS waits long time and doesn't work
    fastify.addHook('preHandler', (req, res, next) => {
      const {session} = req;
      const {sessionId} = session;

      reqCache[sessionId] = session;

      next();
    });
    fastify.addHook('onClose', (fastify, done) => wss.close(done));
    wss.on('connection', wsWrap(fn, wss, corsWhitelist, onlineClientsMap));

    return wss;
  };

  return fastify;
};

```

**Comment by SerayaEryn** [comment]
I think it should be possible. However it would require changes to `fastify-session`:

It would be necessary to extract the part of `fastify-session` that decrypts the session and adds it to the request into a function (lets name it `decryptSession(sessionId, request, done)` for now) and decorate the fastify server with it.
https://github.com/SerayaEryn/fastify-session/blob/f41c5fc8859d6a9e2002dfb33ec2b21972cfbe9e/lib/fastifySession.js#L35-L63

Then you should be able to use the `decryptSession()` function like this:

```js
const {corsWhitelist} = require('../config');
const wsWrap = require('../helpers/ws');
const {cookie} = require('../helpers');
const Server = require('ws/lib/websocket-server');

module.exports = (fastify) => {
  const onlineClientsMap = {};

  fastify.ws = (path, fn) => {
    const reqCache = {};
    const wss = new Server({
      verifyClient: (info, done) => {
        if (!info.req.cookies) {
          info.req.cookies = cookie.getCookieFromHeaders(info.req);
        }
        const {sessionId} = info.req.cookies;

        fastify.decryptSession(sessionId, request, () => {
          // request.session should be available here
          done()
        })
      },
      server: fastify.server,
      path,
    });

    fastify.addHook('onClose', (fastify, done) => wss.close(done));
    wss.on('connection', wsWrap(fn, wss, corsWhitelist, onlineClientsMap));

    return wss;
  };

  return fastify;
};
```

Please feel free to open a PR if this is a solution works for you.

**Comment by dalisoft** [comment]
Hello and thanks for the tip, i tried 3-4 ways, but can't make it work, so i keep data in cookie rather than session. The fastify plugins are so small, i choose performance over flexibility and easy

**Comment by dalisoft** [comment]
In `info.req` not only session, also other things unavailable such as `cookie`, i'm simulating cookies with headers. Other decorated to fastify, request and response also unavailable, very strange case

**Comment by SerayaEryn** [comment]
I am closing this issue now. 
Feel free to open a new one if needed.

**Comment by wesselvdv** [comment]
I think i'll give this approach a go, see if I can validate whether or not it works. Could be a nice in-between until something as major as https://github.com/fastify/fastify-websocket/issues/70 lands.

**Comment by DRoet** [comment]
@wesselvdv Did you figure out a way to get this to work?

**Comment by DRoet** [comment]
For the people that stumble into this thread using `fastify-websocket`.
With `fastify-cookie: '^4.1.0'` && `fastify-session: '^5.1.0'`, you can now do:

```js
fastify.register(require('fastify-websocket'), {
   options: {
      verifyClient (info, done) {
         const { sessionId } = fastify.parseCookie(info.req.headers.cookie)

         if (sessionId) {
            fastify.decryptSession(sessionId, info.req, () => {
               // info.req.session should be available here
            })
         }
      }
   }
})
```
