### ISSUE TITLE
Cookie maxAge is null: store uses default maxAge

### ISSUE THREAD

**Issue by Tiim** [SerayaEryn/fastify-session#53]
## environment

* node v11.2.0
* fastify-session: 2.0.0
* [connect-session-knex](https://github.com/llambda/connect-session-knex): 1.4.0

I'm trying to store sessions in a postgresql database with connect-session-knex. But after inspecting the database i realized that the expire date is always set to the next day (default value hardcoded in connect-session-knex), Instead of after the duration I set in `maxAge`.

The session object looks like this:

```js
Session {
  expires: 2020-04-16T16:30:27.140Z,
  cookie:
   Cookie {
     maxAge: null,
     path: '/',
     httpOnly: true,
     secure: false,
     expires: 2020-04-16T16:30:27.140Z,
     sameSite: null,
     domain: null },
  sessionId: 'TVl_cNQ1_3yiYsngBIC5FjgpcSq5B0E7',
  encryptedSessionId:
   'TVl_cNQ1_3yiYsngBIC5FjgpcSq5B0E7.85waguM8YsWk6tewsX6BXcgek9GMkeL0N8FbenI+gqY',
  user: { id: 1, email: 'test@example.com' },
  [Symbol(maxAge)]: 31536000000,
  [Symbol(secretKey)]: '...' }
```

## configuration

```js
const store = new KnexSessionStore({
  knex,
  tablename: 'session',
  createtable: true,
  clearInterval: 1000 * 60 * 30, //30 Min
});

fastify.register(cookie);
fastify.register(session, {
  cookie: {
    httpOnly: true,
    secure: config.isProduction,
    maxAge: 1000 * 60 * 60 * 24 * 365, //1y
  },
  saveUninitialized: false,
  secret: config.sessionSecret,
  store,
});
```

I dug a bit in the source of connect-session-knex and it seams as if it [uses the maxAge property of the cookie and not the expires property](https://github.com/llambda/connect-session-knex/blob/master/index.js#L279-L284). Is it a bug that the maxAge property is left as `null` or is that intended behavoir? And is it possible to work around this?
Thanks in advance :)

**Comment by SerayaEryn** [comment]
I'll take a look at it.

**Comment by SerayaEryn** [comment]
I published a new version with a fix for this problem.

**Comment by Tiim** [comment]
Thank you very much. Works as expected 👍
