### ISSUE TITLE
Cookie is not deleted from browser, when trying to set it as empty string

### ISSUE THREAD

**Issue by YVeselovskyi** [SerayaEryn/fastify-session#57]
Hello!
I started creating simple fastify server with cookies and session auth, but I have no idea why cookie is not being deleted from browser when accessing logout route?

[Server code](https://gist.github.com/YVeselovskyi/624c83e48cc7143888604a128906d3f8)

Thank you!

**Comment by SerayaEryn** [comment]
`fastify-session` sets its cookie in the `onSend` Hook, which is being executed after your code.

Instead of deleting the cookie you should delete the session from the sessionStore.

```js
request.sessionStore.destroy(request.session.sessionId, (err) => {
  if (err) {
    // ...
  } else {
    request.session = null
    // ...
  }
})
```

**Comment by YVeselovskyi** [comment]
Thanks for your answer, so cookie will not be deleted?
Like in express `res.clearCookie('user_sid');`?
And how I can verify, that current session is over?

**Comment by SerayaEryn** [comment]
I had to correct the example from my previous comment. It is also required to set the session to null.

After the logout you will be redirected and get a new cookie.

I wrote a little working example: https://gist.github.com/SerayaEryn/315a934941a975d0e7b18297f1435f00

**Comment by YVeselovskyi** [comment]
Thank you a lot!
So as I understand the cookie will not be deleted, just replaced with a new one?

**Comment by SerayaEryn** [comment]
Yes, the cookie will replaced.

**Comment by deklanw** [comment]
@SerayaEryn 

I also can't get logging out to work. I followed your example but still nothing. So I checked to see if the store is actually destroying,

```typescript
    ctx.sessionStore.destroy(ctx.session!.sessionId, (err: any) => {
      if (err) {
        console.log('Error deleting session');
      } else {
        console.log('Destroyed', ctx.session);
        ctx.sessionStore.get(ctx.session!.sessionId, (err2: any, sesh: any) => {
          if (err2) {
            console.log('Error getting session');
          } else {
            console.log('Got', sesh);
          }
        });
        ctx.session = null;
      }
    });
```

Console log is this,
```
Destroyed Session {
  expires: 2019-05-17T19:18:25.462Z,
  cookie:
   Cookie {
     maxAge: 604800000,
     path: '/',
     httpOnly: true,
     secure: false,
     expires: 2019-05-17T19:18:25.462Z,
     sameSite: null,
     domain: null },
  sessionId: '_1yLUBzWYIvEnr-0CqacTjOkbslIrbPc',
  encryptedSessionId:
   '_1yLUBzWYIvEnr-0CqacTjOkbslIrbPc.yplR3QnFPVVUVNLHZ6wZIs7lXCm6JVnPKw4lSuG+QEU',
  userId: 3,
  [Symbol(maxAge)]: 604800000,
  [Symbol(secretKey)]: 'fjieosjfoejf09ofjeosijfiosejfoes3j90j)#(#()' }
Got { expires: '2019-05-17T19:18:25.462Z',
  cookie:
   { maxAge: 604800000,
     path: '/',
     httpOnly: true,
     secure: false,
     expires: '2019-05-17T19:18:25.462Z',
     sameSite: null,
     domain: null },
  sessionId: '_1yLUBzWYIvEnr-0CqacTjOkbslIrbPc',
  encryptedSessionId:
   '_1yLUBzWYIvEnr-0CqacTjOkbslIrbPc.yplR3QnFPVVUVNLHZ6wZIs7lXCm6JVnPKw4lSuG+QEU',
  userId: 3 }

```

**Comment by mfpopa** [comment]
Posting this just in case anyone else runs into the same problem like myself or @deklanw.

`request.sessionStore.destroy(...)` only deletes the session from the store, but the session is object still remains on the request and when the `onSend` hook executes, the session is saved back to the store.

The solution is to manually set `request.session = null`. Or even better, use `request.destroySession(cb)` instead of `reuqest.sessionStore.destroy(...)` because it deletes the session from from the store and from the request object.
