### ISSUE TITLE
Knex session store

### ISSUE THREAD

**Issue by ghost** [SerayaEryn/fastify-session#58]
Hello, 
First of all I would like to thank you for the great Module.

I was inspired and created a store session for knex connection especially for this module.

https://github.com/GleisonMv/fast-store-knex

I would like your feedback.

**Comment by SerayaEryn** [comment]
I did a quick review. 
I have some suggestions:

1. I think it would be good to add `request.destroySession(done)` to `fastify-session` instead. It will be usefull even with another store. Would you like to open a PR?
2. It is unlikely a problem, but the `instance` variable is shared between instances of the store being created. I guess in this case it is unintentional? It might be better to store it on your store `this.instance = knex` and access it with `this.instance`.
3. I didn't refactor the default store to ES6 classes yet and it might be just a preference, but I think ES6 classes are more readable than using the prototype.

**Comment by ghost** [comment]
Thank you, I will implement.
