### ISSUE TITLE
302 Redirect does not send cookie header

### ISSUE THREAD

**Issue by willin** [SerayaEryn/fastify-session#61]
<img width="1013" alt="WX20190517-093052@2x" src="https://user-images.githubusercontent.com/1890238/57897292-b2aace80-7886-11e9-80a7-a1c0e96ecbd2.png">
<img width="832" alt="WX20190517-093023@2x" src="https://user-images.githubusercontent.com/1890238/57897296-b4749200-7886-11e9-8394-328c5fdfa6b2.png">

source:

```js
exports.callback = async (req, reply) => {
  const { code = '' } = req.query;
  const { data } = await axios.get(
    `https://api.weixin.qq.com/sns/oauth2/access_token?appid=${ak}&secret=${sk}&code=${code}&grant_type=authorization_code`
  );
  const { access_token: token = '', expires_in: expires, refresh_token: rt, openid } = data;
    req.session.access_token = token;
    req.session.expires_in = getTimestamp() + expires;
    req.session.refresh_token = rt;
    req.session.openid = openid;
  reply.redirect('/');
};
```

**Comment by SerayaEryn** [comment]
Since you are using `http:` and not `https:` as protocol:
Did you pass `cookie: { secure: false }` with the options for `fastify-session`?

**Comment by willin** [comment]
oic...

thx
