### ISSUE TITLE
Switch from preHandler to preValidation

### ISSUE THREAD

**Issue by selesh3** [SerayaEryn/fastify-session#63]
Currently session information is attached only after validation in preHandler Hook.
https://github.com/SerayaEryn/fastify-session/blob/c3f0285fc4a4e377b4eee38f93b98d5c3e99a516/lib/fastifySession.js#L18
So, for example, it is not possible to use information about the session for logging if validation is failed.
What do you think about changing the Hook from preHandler to preValidation?

**Comment by SerayaEryn** [comment]
Sounds reasonable. Would you like to open a PR?

**Comment by SerayaEryn** [comment]
The changes from #64 have been released in v3.0.0.

**Comment by SimenB** [comment]
Any reason this is not using `onRequest`? Being able to access the session data in other `onRequest` hooks is useful (and required for any integration with e.g `fastify-express`)
