### ISSUE TITLE
Request handler called even when response.redirect() is called in preHandler

### ISSUE THREAD

**Issue by ericmacfa** [SerayaEryn/fastify-session#65]
_**Disclaimer:** I'm not absolutely certain whether this ticket is a bug with this plugin, or with Fastify itself, but I was not able to reproduce without using this plugin._

** Summary**
TLDR: A route's handler is still called even when the `preHandler` hook (of the same route) calls `reply.redirect(...)`

I have a route with a `preHandler` hook, and the hook is intended to protect the route by checking if the request is authenticated. If the request is not authenticated, then it is redirected to the login route. However, even when `reply.redirect('/login')` is called inside the route's `preHandler`, the route's handler is still called.

----

**Setup**
1. `npm init -y && npm i -S fastify fastify-cookie fastify-session memorystore ms`
2. Add the code from [this gist](https://gist.github.com/ericmacfa/20f70db342c8aed7feea844a847975aa) to `index.js`
3. `node ./index.js`

**Steps to reproduce**
1. `curl -L localhost:3000` (Or via a browser, postman, etc.)
2. Notice that the server log shows
    ```
    GET / -> preHandler()
    GET / -> handler() !! This should never be shown !!
    GET /login -> handler()
    ```

----

I think it's important to note that this issue does not occur in the following scenarios:
1. An error is thrown after `reply.redirect('/login')`
2. The `preHandler` hook uses the [callback signature](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#requestresponse-hooks), and does not call `next()` if the request is not authenticated

Unfortunately I'm at a loss for where to start with this investigation, this seems like a very wonky issue 🤔

**Comment by ghost** [comment]
is missing a return in function "preHandler: async function (request, reply)"

Correction:
https://gist.github.com/GleisonMV/1c0490d1c82c8fa93ee86c113efb99e9

log:
````
server listening on port 3000
GET /login -> handler()
````

**Comment by ericmacfa** [comment]
Based on the log, it looks like you navigated directly to `/login`, so the hook attached to the `/` route was never called 😕

With that said, a `return;` statement (or `return undefined;`) at the end of a function is equivalent to no return statement at all, so this won't have an impact on the execution.
However, to make sure I'm not going crazy, I did indeed make your change, but the issue persisted.

**Comment by ghost** [comment]
Yes it is, sorry, but what it seems is that the async of the hook, only interrupted the life cycle if it has a throw

**Comment by ghost** [comment]
first test with the initial code
Log:
```
server listening on port 3000
GET / -> preHandler()
GET / -> handler() !! This should never be shown !!
GET /login -> handler()
```

With throw

```
// With this hook, the handler is still called
    preHandler: async function(request, reply) {
        console.log('GET / -> preHandler()');
        reply.redirect('/login');
        throw new Error()
    },
```

log: 
```
server listening on port 3000
GET / -> preHandler()
GET /login -> handler()
```

hooks with async should be used with promise

**Comment by ericmacfa** [comment]
Throwing an error does indeed interrupt the lifecyle. With that said, based on the [fastify hooks documentation](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#respond-to-a-request-from-a-hook), throwing an error should not be required in this case 🤔.


> hooks with async should be used with promise

I'm not quite sure what you mean, could you please elaborate? An `async` function implicitly returns a promise.

**Comment by SerayaEryn** [comment]
It is possible to reproduce the problem only using `fastify` (and `fastify-plugin)`: https://gist.github.com/SerayaEryn/85b85867a81a9d25ad15d9978ce4cfd0

The problem occurs when the callback of the `onSend` hook is not being called synchronous.

Therefore an issue should be opened in the fastify repository.

**Comment by ericmacfa** [comment]
Thanks for the investigation!  
Expanding on your findings, the issue occurs even without `fastify-plugin` 😕
I have opened [an issue](https://github.com/fastify/fastify/issues/1733) in the fastify repository for this.
