### ISSUE TITLE
set-cookie runs for every single request

### ISSUE THREAD

**Issue by anjaneyasivan** [SerayaEryn/fastify-session#67]
https://github.com/SerayaEryn/fastify-session/blob/767dd0f2b8dab76f29202f2a492d0f2dfa198f47/lib/fastifySession.js#L144

I've set maxAge property under cookie option under a secure proxy. For every single request passed to server, the cookie "expires" gets updated with the response. I am a newbie on this. Is this good practice to update cookies on every single request?

**Comment by SerayaEryn** [comment]
I guess that depends on how you want the session to behave.

`fastify-session` keeps the session alive as long as the user makes a request before the cookie expires by updating the cookie on every request.

If you need a session that expires after an amount of time a new option would need to be added to `fastify-session`.
