### ISSUE TITLE
Secure or nonsecure cookie depending on request type

### ISSUE THREAD

**Issue by williamzhao87** [SerayaEryn/fastify-session#84]
Is it possible to set the "Secure" flag or not in the cookie, depending on the request type (secure when it's an https request, nonsecure when it's over http)?

We have a use case where the server receives both http and https requests, but we want to serve only secure cookies to the https requests and non-secure cookies to the http requests.

**Comment by SerayaEryn** [comment]
That is not possible at the moment.

Would you like to open a PR?
