### ISSUE TITLE
Session in production?

### ISSUE THREAD

**Issue by samevision** [SerayaEryn/fastify-session#91]
Hello,

I am using sessions to know if a user is logged in or not. On my local machine everything works fine but on my server I can't save sessions. The user is able to log in but the session will be destroyed immediately.

Any ideas what the problem could be?

Thanks.

**Comment by samevision** [comment]
Okay, I realized two things.

1. The session is only working with the cookie option "secure: false". Even if I am using https in production. I assumed the option has to be set to true while using https. With secure set to true I am not even able to login. The login page will be reloaded.

**login function**
```
const user = await models.User.findOne({
	where: {
		email: req.body.email
	}
})
if (validPassword(user, req.body.password)) {
	req.session.loggedIn = true
	req.session.userId = user.id
	req.session.active = user.active
	res.redirect("/dashboard")
}
```

**middleware after login**
```
if (req.session.loggedIn == true && req.session.active == true) {
	next()
} else if (req.session.loggedIn == true && req.session.active == false) {
	res.send("Please confirm your account.")
} else {
	res.redirect("/login")
}
```

2. If I start the app with clusters, I am able to login, but after that the session will be destroyed immediately.

**cluster.js**
```
var cluster = require('cluster');

if (cluster.isMaster) {
  var cpuCount = require('os').cpus().length;

  console.log('Master cluster setting up ' + cpuCount + ' workers...');

  for (var i = 0; i < cpuCount; i += 1) {
    cluster.fork();
  }

  cluster.on('online', function(worker) {
    console.log('Worker ' + worker.process.pid + ' is online');
  });

  cluster.on('exit', function () {
    console.log('Worker ' + worker.process.pid + ' died with code: ' + code + ', and signal: ' + signal);
    console.log('Starting a new worker');
    cluster.fork();
  });
} else {
  require('./app')
}
```

I appreciate your help.

**Comment by SerayaEryn** [comment]
I missed your issue. Do you still need help?
